- name: Docker Configure in GCP VM-Machine
  hosts: all
  become: true
  connection: ssh
  tasks:
  - name: Updating the New VM machine
    command: sudo yum update

  - name: Install Docker
    command: sudo apt-get install docker.io -y
    become: yes
    become_user: root

  - name: Start Docker service
    command: sudo systemctl start docker
    become: yes
    become_user: root
